analytics: {}
color:
  brandColors:
    - '#C8D0A8'
    - '#56671E'
    - '#000000'
    - '#A8C840'
    - '#E0E8B8'
  brandStrength: 0.92554
  lightness: 0.420655
  rhythmicContrast: 0.147566
  saturation: 0.874029
cta: {}
layout_spectrum: 0.7741628657095134
name: baltimorebreastimplants.com
opengraph: {}
purpose: []
typography_spectrum: 0.2907525240443647
