name: baltimorebreastimplants.com
favicon: null
layout_spectrum: 0.774162
typography_spectrum: 0.29223
title: 'Baltimore breast implants, breast augmentation and cosmetic surgery site.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8D0A8'
    - '#56671E'
    - '#000000'
    - '#A8C840'
    - '#E0E8B8'
  brandStrength: 0.92554
  lightness: 0.420655
  saturation: 0.874029
  rhythmicContrast: 0.147566
purpose: []
