analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#add036'
    - '#c2c5be'
    - '#e1eec2'
    - '#c6de70'
  brandStrength: 0.006757
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.5009
name: baltimorebreastimplants.com
opengraph: {}
purpose: []
typography_spectrum: 0.29223
