name: baltimorebreastimplants.com
favicon: null
layout_spectrum: 0.5009
typography_spectrum: 0.29223
title: 'Baltimore breast implants, breast augmentation and cosmetic surgery site.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#add036'
    - '#c2c5be'
    - '#e1eec2'
    - '#c6de70'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
