name: baltimorebreastimplants.com
favicon: null
layout_spectrum: 0.5009
typography_spectrum: 0.29223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#6f6f6d'
    - '#000000'
    - '#00c9f7'
    - '#ff2fa1'
  brandStrength: 0.006757
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
